### ISSUE TITLE
No link attribute when sending a marker

### ISSUE THREAD

**Issue by sgofferj** [dceejay/TAKreg#6]
When sending a marker as per documentation, the node does not seem to create a link attribute. As far as I understand the CoT specs, this is required when a client sends a CoT about anything else than itself.

I think, when sending a CoT through the node, the node should add a link attribute, something like this:
```
"link": { "_attributes": { "uid": myUID, "production_time": prodTime, "type": myType, "parent_callsign": myCallsign, "relation": "p-p" } },
```
Where myUID, myType and myCallsign are the values in the node configuration, not the values of the CoT being sent.

Edit: Forgot - the link attribute is a sub attribute of \<details/\>.

**Comment by sgofferj** [comment]
Example: I ("Wolfman", a-f-G-U) sent a CoT for the Tampere Bus Station a-u-G-E-V.
```
<event version='2.0' uid='03549527-7d6f-4033-827a-e9d82c9f3e31'
  type='a-u-G-E-V'
  time='2024-05-21T17:58:32Z'
  start='2024-05-21T17:58:32Z'
  stale='2025-05-21T17:58:32Z'
  how='h-g-i-g-o'
>
  <point lat='61.4937163' lon='23.769567' hae='106.691' ce='9999999.0' le='9999999.0' />
  <detail>
    <contact callsign="Tampere Bus Station"/>
    <status readiness="true"/>
    <color argb="-1"/>
    <precisionlocation altsrc="DTED0"/>
    <link uid="ANDROID-e1e1b58539969a32"
      production_time="2024-05-21T17:58:32.334Z"
      type="a-f-G-U"
      parent_callsign="Wolfman"
      relation="p-p"/>
    <remarks/>
    <usericon iconsetpath="f7f71666-8b28-4b57-9fbb-e38e61d33b79/Google/bus.png"/>
  </detail>
</event>
```

**Comment by dceejay** [comment]
Thanks - will have a look.
On a trip until end June so won't be until July
(but of course PR's welcome)

**Comment by dceejay** [comment]
Thanks @sgofferj , have added the link for positions that aren't "me".  version 0.12.0
Of course if the payload is raw xml I do just pass it through - so I won't handle that - but for anything in json "worldmap" format it will get added.
